config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' } 
  devise_for :users, controllers: { sessions: 'users/sessions' }                             
  resources :zombies do
  resources :brains
  end 
  root to: 'zombies#index'
devise_scope :admin do
	get 'admins/users/list', to: 'admins/sessions#list', as: 'users_list'
end


  get '/cerebros', to: 'brains#index', as: 'brains'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Zombies" %></title>
<link rel="stylesheet" href="stylesheets/style.css" />




<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div data-sticky-container id="example-menu">
  <div class="small-12 sticky" data-sticky data-options="marginTop: 0">
     <div class="top-bar">
      <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu >
  <li class="active"><a href = "#">Zombies</a></li>
  <% if user_signed_in? && admin_signed_in?%>
  <li><a>Despliegame</a>
  <ul class="menu">
    <% if current_user.role === "suscriber" %>
    <li><%= link_to 'Indice de Zombies', zombies_path %></li>
   <%else%>
   <li><%= link_to 'New Zombie', new_zombie_path %></li>
    <li><%= link_to 'Indice de Zombies', zombies_path %></li>
    <%end%>
</ul>
</li> <% end %>
</ul>
</div>
<div class="top-bar-right">
  <ul class="menu">
<% if admin_signed_in? %> 
    <li> Bienvenido(a) <%= current_admin.email %></li>
    <li><%= link_to 'Edit profile', edit_admin_registration_path %></li>
    <li><%= link_to 'Logout', destroy_admin_session_path, method: :delete %></li>
    

    <% elsif user_signed_in? %>
    <li> Bienvenido(a) <%= current_user.email %></li>
    <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Login',  new_user_session_path %></li>
      <li><%= link_to 'Signup',  new_user_registration_path %></li>
    <% end %>
    
  </ul>
</div>
</div>
</div>
</div>
<% if notice %>
    <p class="alert alert-success"><%= notice %> </p><% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %> </p><% end %>
<br><br>


    <div class="container">
      <% flash.each do |key, value| %>
        <div class='alert alert-<%=key%>'><%= value %></div>
      <% end %>
    </div>



    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <%= yield %>

  </body>
</html>